apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp-deployment
  namespace: mateapp
  labels:
    app: todolist
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: todolist
  template:
    metadata:
      labels:
        app: todolist
    spec:
      containers:
      - name: todoapp-container
        image: baga56789/todoapp:3.0.0
        ports:
        - name: web-port
          containerPort: 8000
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: DJANGO_SETTINGS_MODULE
          value: "todolist.settings"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /api/liveness/
            port: web-port
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/readiness/
            port: web-port
          initialDelaySeconds: 5
          periodSeconds: 10
